# ------------------------------------------------------------------------------
# Chest Settings Documentation
#
# This file configures how chests are populated in specific biomes using a
# weight-based system. Each chest configuration respects a global "MaxItemsPerSlot"
# setting which limits the number of items that can appear in any one slot.(Does not apply to Minecraft-based Loot Tables)
#
# The plugin supports two modes:
#
# 1) Custom Loot Tables:
#
#    In Custom Loot Tables mode you explicitly define which items appear in a chest.
#    Two formats are supported:
#
#    [Legacy (Compact) Format]
#
#    ChestSettings:
#      ChestOld:
#        Items: [MATERIAL_ENUM:weight:maxAmount]
#        Biomes: [BIOME_ENUM]
#
#    [New Expanded Format]
#
#     ChestSettings:                                     # ChestSettings (Parent Key) Under this key, create one or more named chest configurations (e.g., "Chest1").
#       ChestNew:
#         Items:
#           - MATERIAL_ENUM:                            # Use the exact item names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
#             - Weight: <numeric value>                 # The chance (in percent) for the material to be placed in the chest.
#             - MaxAmount: <numeric value>              # The max amount of that material that will be allowed chest wide.
#             - CustomName: <custom display name>       # Supports use of Minecraft color codes like "§0" for Black and so on.
#             - LevelType: <Standard or Roman>          # Item-wide setting for enchantment display
#             - Enchantments:
#                 - ENCHANTMENT_ENUM:                   # Use exact enchantment names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/enchantments/Enchantment.html
#                     - Weight: <numeric chance in percent>
#                     - MinLevel: <minimum level>
#                     - MaxLevel: <maximum level>
#                     - LoreColor: <color>             # (Optional) Valid colors: BLACK, DARK_BLUE, DARK_GREEN,DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY,DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE,YELLOW, WHITE.
#         Biomes:
#           - BIOME_ENUM                               # Use the exact biome names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/block/Biome.html
#
#      This format offers additional customization:
#
#        - CustomName: Set a custom display name (supports Minecraft color codes, e.g., "§6HolyDirt").
#        - LevelType: Item-wide setting for how enchantment levels are displayed.
#                     Options:
#                        * Standard – e.g., "lvl_1", "lvl_2".
#                        * Roman – e.g., "I", "II" (defaults to Roman if omitted or unrecognized).
#        - Enchantments: For each enchantment, specify:
#                         * Weight: Chance (in percent) for the enchantment to be applied.
#                         * MinLevel and MaxLevel: Range for the enchantment level.
#                         * LoreColor: Color used for the enchantment display in the item's lore.
#                           Valid colors include: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED,DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE.
#
#      Example (provided in comments):
#
#      ChestSettings:
#        ChestExpanded:
#          Items:
#            - MYCELIUM:
#                - Weight: 30
#                - MaxAmount: 5
#                - CustomName: §6HolyDirt
#                - LevelType: Standard
#                - Enchantments:
#                    - FORTUNE:
#                        - Weight: 100
#                        - MinLevel: 1
#                        - MaxLevel: 400
#                        - LoreColor: RED
#            - AIR:
#                - Weight: 90
#                - MaxAmount: 999
#          Biomes:
#            - MUSHROOM_FIELDS
#
# 2) Minecraft-based Loot Tables:
#
#    In this mode vanilla Minecraft loot generation is used. Instead of an "Items" section,
#    you define a "LootTables" section with one or more loot table entries.
#
#    Formatting:
#
#      Each loot table entry is defined as a map where the key is a loot table enum (from
#      Bukkit’s LootTables, such as SIMPLE_DUNGEON, ABANDONED_MINESHAFT, etc.) and the value
#      is a list containing a "Weight" property.
#      Bukkit LootTables: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/loot/LootTables.html
#
#      Example (provided in comments):
#
#      ChestSettings:
#        ChestVanilla:
#          LootTables:
#            - ABANDONED_MINESHAFT:
#                - Weight: 100
#          Biomes: [BIRCH_FOREST, DRIPSTONE_CAVES, LUSH_CAVES]
#
#      Another Example:
#
#      ChestSettings:
#        ChestMulti:
#          LootTables:
#            - SIMPLE_DUNGEON:
#                - Weight: 80.6
#            - VILLAGE_ARMORER:
#                - Weight: 19.4
#          Biomes: [DESERT, FOREST, PLAINS]
#
# Additional Notes:
#
#   - Advanced Weighting: In Custom Loot Tables mode, you can use filler items (such as AIR)
#     with high weight values to lower the odds of rare items appearing.
#
#   - maxAmount vs. MaxItemsPerSlot:
#       * maxAmount: Maximum total number of a given item allowed in the chest.
#       * MaxItemsPerSlot: Maximum number of that item that can appear in any one slot.(Not needed if using Minecraft-based Loot Tables)
#
#   - YAML Tips:
#       * Both the compact and expanded formats are supported for custom loot tables.
#       * For vanilla loot tables, use the enum names from Bukkit’s LootTables.
#
# ------------------------------------------------------------------------------
#
# You can define multiple chest configurations for different biome groups.
#
# Overworld Biomes:
#
MaxItemsPerSlot: 2

ChestSettings:
  CustomChest1:
    Items:
      - MYCELIUM:30:5
      - RED_MUSHROOM:20:5
      - BROWN_MUSHROOM:20:5
      - RED_MUSHROOM_BLOCK:10:5
      - BROWN_MUSHROOM_BLOCK:10:5
      - MUSHROOM_STEM:10:5
    Biomes:
      - MUSHROOM_FIELDS
  CustomChest2:
    Items:
      - WOODEN_AXE:
        - Weight: 20
        - MaxAmount: 1
        - Enchantments:
          - VANISHING_CURSE:
            - Weight: 50
            - MinLevel: 1
            - MaxLevel: 1
          - EFFICIENCY:
            - Weight: 70
            - MinLevel: 1
            - MaxLevel: 4
          - UNBREAKING:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 3
      - WOODEN_PICKAXE:
        - Weight: 20
        - MaxAmount: 1
        - Enchantments:
          - VANISHING_CURSE:
            - Weight: 50
            - MinLevel: 1
            - MaxLevel: 1
          - EFFICIENCY:
            - Weight: 40
            - MinLevel: 1
            - MaxLevel: 4
          - FORTUNE:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 3
          - UNBREAKING:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 3
      - CROSSBOW:
        - Weight: 20
        - MaxAmount: 1
        - Enchantments:
          - VANISHING_CURSE:
            - Weight: 50
            - MinLevel: 1
            - MaxLevel: 1
          - MULTISHOT:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 1
          - PIERCING:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 4
          - QUICK_CHARGE:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 3
          - UNBREAKING:
            - Weight: 30
            - MinLevel: 1
            - MaxLevel: 3
      - NAME_TAG:20:1
      - GOLDEN_APPLE:20:1
      - ENCHANTED_GOLDEN_APPLE:20:1
      - APPLE:40:2, OAK_LOG:40:2
      - DARK_OAK_LOG:40:2
      - RAIL:40:2
      - DIAMOND:40:2
      - STRING:90:5
      - ARROW:90:5
      - STICK:90:5
      - WHEAT:90:5
      - IRON_INGOT:90:5
      - TORCH:90:5
      - ARMADILLO_SCUTE:10:2
      - MACE:2:1
      - OMINOUS_BOTTLE:10:2
      - OMINOUS_TRIAL_KEY:2:1
      - TRIAL_KEY:2:1
      - BREEZE_ROD:10:2
      - RESIN_CLUMP:10:2
    Biomes: [BADLANDS, BAMBOO_JUNGLE, BIRCH_FOREST, CHERRY_GROVE, DARK_FOREST, DESERT, DRIPSTONE_CAVES, ERODED_BADLANDS, FLOWER_FOREST, FOREST, GROVE, JAGGED_PEAKS, JUNGLE, LUSH_CAVES, MANGROVE_SWAMP, MEADOW, OLD_GROWTH_BIRCH_FOREST, OLD_GROWTH_PINE_TAIGA, OLD_GROWTH_SPRUCE_TAIGA, PLAINS, SAVANNA, SAVANNA_PLATEAU, SPARSE_JUNGLE, STONY_PEAKS, STONY_SHORE, SUNFLOWER_PLAINS, SWAMP, TAIGA, WINDSWEPT_FOREST, WINDSWEPT_GRAVELLY_HILLS, WINDSWEPT_HILLS, WINDSWEPT_SAVANNA, WOODED_BADLANDS, OCEAN, WARM_OCEAN, LUKEWARM_OCEAN, FROZEN_OCEAN, DEEP_FROZEN_OCEAN, DEEP_LUKEWARM_OCEAN, DEEP_OCEAN, DEEP_COLD_OCEAN, COLD_OCEAN, FROZEN_RIVER, RIVER, BEACH, SNOWY_BEACH, SNOWY_PLAINS, SNOWY_SLOPES, SNOWY_TAIGA, FROZEN_PEAKS, ICE_SPIKES, PALE_GARDEN]
  VanillaChest1:
    LootTables:
      - ANCIENT_CITY:
          - Weight: 100
      - ANCIENT_CITY_ICE_BOX:
          - Weight: 100
    Biomes:
     - DEEP_DARK
#
#Nether Biomes:
#
  Chest3:
    Items: [GOLDEN_APPLE:20:1, ENCHANTED_GOLDEN_APPLE:20:1, GOLD_BLOCK:20:1, GOLDEN_AXE:20:1, IRON_BLOCK:20:1, SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE:20:1, NETHERITE_UPGRADE_SMITHING_TEMPLATE:20:1, IRON_SWORD:20:1, GOLDEN_HELMET:20:1, MUSIC_DISC_PIGSTEP:20:1, DIAMOND:40:2, ANCIENT_DEBRIS:40:2, BONE_BLOCK:40:2, GOLDEN_CARROT:40:2, OBSIDIAN:40:2, CRYING_OBSIDIAN:40:2, IRON_INGOT:90:5, GILDED_BLACKSTONE:90:5, CHAIN:90:5, GOLD_INGOT:90:5, MAGMA_CREAM:90:5, GOLD_NUGGET:90:5, SPECTRAL_ARROW:90:5, STRING:90:5, IRON_NUGGET:90:5, ARROW:90:5, COOKED_PORKCHOP:90:5]
    Biomes: [BASALT_DELTAS, NETHER_WASTES, CRIMSON_FOREST, SOUL_SAND_VALLEY, WARPED_FOREST]
#
# End Biomes Example:
#
  Chest4:
    Items: [ELYTRA:20:1, DRAGON_HEAD:20:1, DRAGON_EGG:20:1, END_CRYSTAL:20:1, ENDER_CHEST:20:1, SHULKER_SHELL:40:2, DIAMOND:40:2, END_ROD:90:5, PURPUR_BLOCK:90:5, MAGENTA_STAINED_GLASS:90:5, GOLD_INGOT:90:5, IRON_INGOT:90:5, OBSIDIAN:90:5]
    Biomes: [THE_END, END_BARRENS, END_HIGHLANDS, END_MIDLANDS, SMALL_END_ISLANDS]
#
# Note: To add additional chest configurations (e.g., Chest5, Chest6, etc.),
# simply create a new key under ChestSettings with its own Items and Biomes.
#
