# ------------------------------------------------------------------------------
#  Chest Settings
#
#  This file configures how chests are populated in specific biomes, using a
#  weight-based system for random item selection. Each chest configuration
#  also respects a global "MaxItemsPerSlot" to control the number of items that
#  can appear in any single slot.
# ------------------------------------------------------------------------------
#
#  1) MaxItemsPerSlot (Global)
#     - Sets a hard limit on how many items of a single type can be placed in
#       one slot, regardless of its maxAmount. Default: 2
# 
#  2) ChestSettings (Parent Key)
#     - Under this, you create one or more named chest configs (e.g., "Chest1").
#     - Each chest config has:
#        a) Items: A list of item entries with the format:
#           ITEM_NAME:weight:maxAmount
#           - ITEM_NAME: Must be a valid Bukkit Material
#           - weight: A numeric "likelihood" relative to other items
#           - maxAmount: The total maximum items of that type allowed
#        b) Biomes: A list of biomes where this chest config applies.
#
#  3) How the Code Chooses Items (Weight-Based):
#     - The plugin sums all item 'weight' values in a chest config, then picks
#       an item for each empty slot in proportion to those weights.
#       Example: If you have four items each with weight 5, total weight is 20.
#       Each item has a (5/20) = 25% chance per slot.
# 
#  4) Reducing Item Chance (Dummy Items):
#     - If you want to lower the overall chance of getting a high-value item,
#       you can add a large-weight "dummy" item, like 'AIR', to dilute the
#       valuable item's share of total weight.
#
#  5) maxAmount vs. MaxItemsPerSlot
#     - maxAmount = total max of that item in the entire chest.
#     - MaxItemsPerSlot (here at the top) = how many of the item can appear
#       in any individual slot.
#
#  6) YAML Tips:
#     - Use standard YAML rules for naming chest configurations. 
#       Alphanumeric, underscores, or quoted strings if you have spaces/special chars.
#     - The plugin supports both "expanded" and "compact" YAML list styles.
#
# ------------------------------------------------------------------------------

MaxItemsPerSlot: 2

ChestSettings:
  Chest1:
    Items:
      - MYCELIUM:30:5
      - RED_MUSHROOM:20:5
      - BROWN_MUSHROOM:20:5
      - RED_MUSHROOM_BLOCK:10:5
      - BROWN_MUSHROOM_BLOCK:10:5
      - MUSHROOM_STEM:10:5
    Biomes:
      - MUSHROOM_FIELDS

# Explanation of the example above:
#   - 'Chest1' is a custom identifier for this chest configuration.
#   - 'Items' are listed in "MATERIAL:weight:maxAmount" format.
#       * MYCELIUM:30:5   => weight=30, maxAmount=5
#       * RED_MUSHROOM:20:5   => weight=20, maxAmount=5
#       etc.
#
#   The code will sum all item weights (30 + 20 + 20 + 10 + 10 + 10 = 100),
#   so MYCELIUM is 30/100 = 30% chance per slot, RED_MUSHROOM is 20%, etc.
#   Once an item exceeds its maxAmount (5 total in this example), it won't
#   be chosen again.
#
#   MaxItemsPerSlot is a global setting at the top of this file (default 2),
#   so even if maxAmount is 5, each slot can only hold up to 2 items.
#
#   'Biomes: [MUSHROOM_FIELDS]' indicates that this config is used whenever
#   a chest is generated in the MUSHROOM_FIELDS biome.

# Note: If you want to add more chest configs (like Chest2, Chest3, etc.),
# just create another key under ChestSettings with its own Items/Biomes.


#Overworld Biomes

  Chest2:
    Items: [WOODEN_AXE:20:1, WOODEN_PICKAXE:20:1, CROSSBOW:20:1, NAME_TAG:20:1, GOLDEN_APPLE:20:1, ENCHANTED_GOLDEN_APPLE:20:1, APPLE:40:2, OAK_LOG:40:2, DARK_OAK_LOG:40:2, RAIL:40:2, DIAMOND:40:2, STRING:90:5, ARROW:90:5, STICK:90:5, WHEAT:90:5, IRON_INGOT:90:5, TORCH:90:5, ARMADILLO_SCUTE:10:2, MACE:2:1, OMINOUS_BOTTLE:10:2, OMINOUS_TRIAL_KEY:2:1, TRIAL_KEY:2:1, BREEZE_ROD:10:2, RESIN_CLUMP:10:2]
    Biomes: [BADLANDS, BAMBOO_JUNGLE, BIRCH_FOREST, CHERRY_GROVE, DARK_FOREST, DESERT, DRIPSTONE_CAVES, ERODED_BADLANDS, FLOWER_FOREST, FOREST, GROVE, JAGGED_PEAKS, JUNGLE, LUSH_CAVES, MANGROVE_SWAMP, MEADOW, OLD_GROWTH_BIRCH_FOREST, OLD_GROWTH_PINE_TAIGA, OLD_GROWTH_SPRUCE_TAIGA, PLAINS, SAVANNA, SAVANNA_PLATEAU, SPARSE_JUNGLE, STONY_PEAKS, STONY_SHORE, SUNFLOWER_PLAINS, SWAMP, TAIGA, WINDSWEPT_FOREST, WINDSWEPT_GRAVELLY_HILLS, WINDSWEPT_HILLS, WINDSWEPT_SAVANNA, WOODED_BADLANDS, OCEAN, WARM_OCEAN, LUKEWARM_OCEAN, FROZEN_OCEAN, DEEP_FROZEN_OCEAN, DEEP_LUKEWARM_OCEAN, DEEP_OCEAN, DEEP_COLD_OCEAN, COLD_OCEAN, FROZEN_RIVER, RIVER, BEACH, SNOWY_BEACH, SNOWY_PLAINS, SNOWY_SLOPES, SNOWY_TAIGA, FROZEN_PEAKS, ICE_SPIKES, DEEP_DARK, PALE_GARDEN]


# Nether Biomes:

  Chest3:
    Items: [GOLDEN_APPLE:20:1, ENCHANTED_GOLDEN_APPLE:20:1, GOLD_BLOCK:20:1, GOLDEN_AXE:20:1, IRON_BLOCK:20:1, SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE:20:1, NETHERITE_UPGRADE_SMITHING_TEMPLATE:20:1, IRON_SWORD:20:1, GOLDEN_HELMET:20:1, MUSIC_DISC_PIGSTEP:20:1, DIAMOND:40:2, ANCIENT_DEBRIS:40:2, BONE_BLOCK:40:2, GOLDEN_CARROT:40:2, OBSIDIAN:40:2, CRYING_OBSIDIAN:40:2, IRON_INGOT:90:5, GILDED_BLACKSTONE:90:5, CHAIN:90:5, GOLD_INGOT:90:5, MAGMA_CREAM:90:5, GOLD_NUGGET:90:5, SPECTRAL_ARROW:90:5, STRING:90:5, IRON_NUGGET:90:5, ARROW:90:5, COOKED_PORKCHOP:90:5]
    Biomes: [BASALT_DELTAS, NETHER_WASTES, CRIMSON_FOREST, SOUL_SAND_VALLEY, WARPED_FOREST]


#End Biomes

  Chest4:
    Items: [ELYTRA:20:1, DRAGON_HEAD:20:1, DRAGON_EGG:20:1, END_CRYSTAL:20:1, ENDER_CHEST:20:1, SHULKER_SHELL:40:2, DIAMOND:40:2, END_ROD:90:5, PURPUR_BLOCK:90:5, MAGENTA_STAINED_GLASS:90:5, GOLD_INGOT:90:5, IRON_INGOT:90:5, OBSIDIAN:90:5]
    Biomes: [THE_END, END_BARRENS, END_HIGHLANDS, END_MIDLANDS, SMALL_END_ISLANDS]