# ------------------------------------------------------------------------------
# Chest Settings Documentation
#
# This file configures how chests are populated in specific biomes using a
# weight-based system. Each chest configuration respects a global "MaxItemsPerSlot"
# setting which limits the number of items that can appear in any one slot.
# (Does not apply to Minecraft-based Loot Tables)
#
# The plugin supports two modes:
#
# 1) Custom Loot Tables:
#
#    In Custom Loot Tables mode you explicitly define which items appear in a chest.
#    Two formats are supported:
#
#    [Legacy (Compact) Format]
#
#    ChestSettings:
#      ChestOld:
#        Items: [MATERIAL_ENUM:weight:maxAmount]
#               [MATERIAL_ENUM:weight:minAmount-maxAmount]
#               # - weight: chance in percent that the material is chosen
#               # - maxAmount: maximum total of that material in the chest
#               # - minAmount (optional): minimum total of that material in the chest, if omitted, defaults to 0 (preserves existing behavior)
#        Biomes: [BIOME_ENUM]
#
#      Example Compact Entries:
#        - DIAMOND:10:1-3     # 10% chance, between 1 and 3 diamonds total
#        - STICK:50:5         # 50% chance, up to 5 sticks (min defaults to 0)
#
#    [New Expanded Format]
#
#     ChestSettings:                                    # Top-level key
#       ChestNew:                                       # Unique chest name
#         Items:
#           - MATERIAL_ENUM:                            # Exact names from Bukkit’s Material enum
#             - Weight: <numeric value>                 # Chance in percent to include
#             - MinAmount: <numeric value>              # OPTIONAL: minimum total amount (defaults to 0)
#             - MaxAmount: <numeric value>              # Maximum total amount in the chest
#             - CustomName: <custom display name>       # Supports Minecraft color codes
#             - LevelType: <Standard or Roman>          # Enchantment display style
#             - Enchantments:
#                 - ENCHANTMENT_ENUM:                   # Exact names from Bukkit’s Enchantment enum
#                     - Weight: <numeric chance in percent>
#                     - MinLevel: <minimum level>
#                     - MaxLevel: <maximum level>
#                     - LoreColor: <color>               # Optional, see valid colors below
#         Biomes:
#           - BIOME_ENUM                               # Exact names from Bukkit’s Biome enum
#
#      This format offers additional customization:
#        • MinAmount: explicitly set the minimum number of that item chest-wide.
#        • MaxAmount: upper cap on that item in the chest.
#        • CustomName: display name with color codes (e.g., "§6HolyDirt").
#        • LevelType: how enchant levels render (Standard or Roman).
#        • Enchantments: specify weight, level range, and lore color per enchant.
#
#      Example Expanded Entry:
#        - MYCELIUM:
#            - Weight: 30
#            - MinAmount: 2
#            - MaxAmount: 5
#            - CustomName: §6HolyDirt
#            - LevelType: Standard
#            - Enchantments:
#                - FORTUNE:
#                    - Weight: 100
#                    - MinLevel: 1
#                    - MaxLevel: 3
#                    - LoreColor: RED
#
# 2) Minecraft-based Loot Tables:
#
#    In this mode vanilla Minecraft loot generation is used. Instead of an "Items" section,
#    you define a "LootTables" section with one or more loot table entries.
#
#    Formatting:
#
#      Each loot table entry is defined as a map where the key is a loot table enum (from
#      Bukkit’s LootTables, such as SIMPLE_DUNGEON, ABANDONED_MINESHAFT, etc.) and the value
#      is a list containing a "Weight" property.
#      Bukkit LootTables: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/loot/LootTables.html
#
#      Example:
#
#      ChestSettings:
#        ChestVanilla:
#          LootTables:
#            - ABANDONED_MINESHAFT:
#                - Weight: 100
#          Biomes: [BIRCH_FOREST, DRIPSTONE_CAVES, LUSH_CAVES]
#
#      Another Example:
#
#      ChestSettings:
#        ChestMulti:
#          LootTables:
#            - SIMPLE_DUNGEON:
#                - Weight: 80.6
#            - VILLAGE_ARMORER:
#                - Weight: 19.4
#          Biomes: [DESERT, FOREST, PLAINS]
#
# Additional Notes:
#
#   - Advanced Weighting: In Custom Loot Tables mode, you can use filler items (such as AIR)
#     with high weight values to lower the odds of rare items appearing.
#
#   - maxAmount vs. MaxItemsPerSlot:
#       * maxAmount: Maximum total number of a given item allowed in the chest.
#       * MaxItemsPerSlot: Maximum number of that item that can appear in any one slot.(Not needed if using Minecraft-based Loot Tables only)
#
#   - MinAmount only applies in Custom Loot Tables mode; if omitted, it’s treated as 0.
#
#   - YAML Tips:
#       * Both the compact and expanded formats are supported for custom loot tables.
#       * For vanilla loot tables, use the enum names from Bukkit’s LootTables.
#
# ------------------------------------------------------------------------------
#
# You can define multiple chest configurations for different biome groups.
#
# Overworld Biomes:
#

MaxItemsPerSlot: 3 # Does not apply to Minecraft loot table chest types, just needed for custom chest.

ChestSettings:
  Custom_Chest1:
    Items:
      - BROWN_MUSHROOM:20:5
      - BROWN_MUSHROOM_BLOCK:10:5
      - MUSHROOM_STEM:10:5
      - MYCELIUM:30:5
      - RED_MUSHROOM:20:5
      - RED_MUSHROOM_BLOCK:10:5
    Biomes:
      - MUSHROOM_FIELDS
  Vanilla_Overworld_Desert:
    LootTables:
      - DESERT_PYRAMID:
          - Weight: 100
      - DESERT_PYRAMID_ARCHAEOLOGY:
          - Weight: 100
      - DESERT_WELL_ARCHAEOLOGY:
          - Weight: 100
      - VILLAGE_DESERT_HOUSE:
          - Weight: 100
    Biomes:
      - DESERT

  Vanilla_Overworld_Jungle:
    LootTables:
      - JUNGLE_TEMPLE:
          - Weight: 100
      - JUNGLE_TEMPLE_DISPENSER:
          - Weight: 100
    Biomes:
      - BAMBOO_JUNGLE
      - JUNGLE
      - SPARSE_JUNGLE

  Vanilla_Overworld_DarkForest:
    LootTables:
      - WOODLAND_MANSION:
          - Weight: 100
    Biomes:
      - DARK_FOREST

  Vanilla_Overworld_DeepDark:
    LootTables:
      - ANCIENT_CITY:
          - Weight: 100
      - ANCIENT_CITY_ICE_BOX:
          - Weight: 100
    Biomes:
      - DEEP_DARK

  Vanilla_Overworld_Village_Plains:
    LootTables:
      - VILLAGE_PLAINS_HOUSE:
          - Weight: 100
    Biomes:
      - PLAINS

  Vanilla_Overworld_Village_Snowy:
    LootTables:
      - VILLAGE_SNOWY_HOUSE:
          - Weight: 100
    Biomes:
      - SNOWY_PLAINS

  Vanilla_Overworld_Village_Taiga:
    LootTables:
      - VILLAGE_TAIGA_HOUSE:
          - Weight: 100
    Biomes:
      - TAIGA

  Vanilla_Overworld_Village_Savanna:
    LootTables:
      - VILLAGE_SAVANNA_HOUSE:
          - Weight: 100
    Biomes:
      - SAVANNA

  Vanilla_Overworld_Generic:
    LootTables:
      - ABANDONED_MINESHAFT:
          - Weight: 100
      - ELDER_GUARDIAN:
          - Weight: 100
      - PILLAGER_OUTPOST:
          - Weight: 100
      - RUINED_PORTAL:
          - Weight: 100
      - SHIPWRECK_MAP:
          - Weight: 100
      - SHIPWRECK_SUPPLY:
          - Weight: 100
      - SHIPWRECK_TREASURE:
          - Weight: 100
      - SIMPLE_DUNGEON:
          - Weight: 100
      - STRONGHOLD_CORRIDOR:
          - Weight: 100
      - STRONGHOLD_CROSSING:
          - Weight: 100
      - STRONGHOLD_LIBRARY:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD_OMINOUS:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD_OMINOUS_RARE:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD_OMINOUS_UNIQUE:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD_RARE:
          - Weight: 100
      - TRIAL_CHAMBERS_REWARD_UNIQUE:
          - Weight: 100
      - UNDERWATER_RUIN_BIG:
          - Weight: 100
      - UNDERWATER_RUIN_SMALL:
          - Weight: 100
      - VILLAGE_ARMORER:
          - Weight: 100
    Biomes:
      - BADLANDS
      - BIRCH_FOREST
      - CHERRY_GROVE
      - DRIPSTONE_CAVES
      - ERODED_BADLANDS
      - FLOWER_FOREST
      - FOREST
      - GROVE
      - JAGGED_PEAKS
      - LUSH_CAVES
      - MANGROVE_SWAMP
      - MEADOW
      - OLD_GROWTH_BIRCH_FOREST
      - OLD_GROWTH_PINE_TAIGA
      - OLD_GROWTH_SPRUCE_TAIGA
      - SAVANNA_PLATEAU
      - STONY_PEAKS
      - STONY_SHORE
      - SUNFLOWER_PLAINS
      - SWAMP
  CustomChest2:
    Items:
      - APPLE:140:6
      - ARMADILLO_SCUTE:5:2
      - ARROW:100:16
      - BOLT_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - BREAD:60:3
      - BREEZE_ROD:5:2
      - COAST_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - COOKED_BEEF:60:4
      - COOKED_CHICKEN:60:4
      - COOKED_PORKCHOP:60:4
      - CROSSBOW:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - MULTISHOT:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 1
              - PIERCING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 4
              - QUICK_CHARGE:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
      - DARK_OAK_LOG:140:8
      - DIAMOND:10:2
      - DUNE_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - EYE_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - ENCHANTED_GOLDEN_APPLE:5:1
      - FLOW_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - GOLDEN_APPLE:5:1
      - GOLDEN_AXE:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - EFFICIENCY:
                  - Weight: 70
                  - MinLevel: 1
                  - MaxLevel: 4
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - FORTUNE:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - MENDING:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
      - GOLDEN_HOE:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - EFFICIENCY:
                  - Weight: 40
                  - MinLevel: 1
                  - MaxLevel: 4
              - FORTUNE:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - MENDING:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
      - GOLDEN_PICKAXE:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - EFFICIENCY:
                  - Weight: 40
                  - MinLevel: 1
                  - MaxLevel: 4
              - FORTUNE:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - SILK_TOUCH:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
              - MENDING:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
      - GOLDEN_SHOVEL:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - EFFICIENCY:
                  - Weight: 40
                  - MinLevel: 1
                  - MaxLevel: 4
              - FORTUNE:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - SILK_TOUCH:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
              - MENDING:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
      - GOLDEN_SWORD:
          - Weight: 20
          - MaxAmount: 1
          - Enchantments:
              - VANISHING_CURSE:
                  - Weight: 50
                  - MinLevel: 1
                  - MaxLevel: 1
              - SHARPNESS:
                  - Weight: 40
                  - MinLevel: 1
                  - MaxLevel: 5
              - UNBREAKING:
                  - Weight: 30
                  - MinLevel: 1
                  - MaxLevel: 3
              - FIRE_ASPECT:
                  - Weight: 20
                  - MinLevel: 1
                  - MaxLevel: 2
              - LOOTING:
                  - Weight: 10
                  - MinLevel: 1
                  - MaxLevel: 3
              - KNOCKBACK:
                  - Weight: 10
                  - MinLevel: 1
                  - MaxLevel: 2
              - SMITE:
                  - Weight: 10
                  - MinLevel: 1
                  - MaxLevel: 5
              - SWEEPING_EDGE:
                  - Weight: 10
                  - MinLevel: 1
                  - MaxLevel: 3
              - WIND_BURST:
                  - Weight: 10
                  - MinLevel: 1
                  - MaxLevel: 3
              - MENDING:
                  - Weight: 5
                  - MinLevel: 1
                  - MaxLevel: 1
      - HOST_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - IRON_INGOT:190:8
      - MACE:1:1
      - NAME_TAG:10:1
      - OAK_LOG:140:8
      - OMINOUS_BOTTLE:1:2
      - OMINOUS_TRIAL_KEY:1:1
      - RAISER_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - RAIL:140:2
      - RESIN_CLUMP:5:2
      - SHAPER_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - STICK:190:6
      - STRING:100:5
      - TORCH:190:5
      - TRIAL_KEY:1:1
      - TIDE_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - VEX_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - WARD_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - WAYFINDER_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - WILD_ARMOR_TRIM_SMITHING_TEMPLATE:1:1
      - WHEAT:190:6
    Biomes: [BEACH, COLD_OCEAN, DEEP_COLD_OCEAN, DEEP_FROZEN_OCEAN, DEEP_LUKEWARM_OCEAN, DEEP_OCEAN, FROZEN_OCEAN, FROZEN_PEAKS, FROZEN_RIVER, ICE_SPIKES, LUKEWARM_OCEAN, OCEAN, PALE_GARDEN, RIVER, SNOWY_BEACH, SNOWY_SLOPES, SNOWY_TAIGA, WARM_OCEAN, WINDSWEPT_FOREST, WINDSWEPT_GRAVELLY_HILLS, WINDSWEPT_HILLS, WINDSWEPT_SAVANNA, WOODED_BADLANDS]
#
#Nether Biomes:
#
  Custom_Chest3:
    Items: [ANCIENT_DEBRIS:40:2, ARROW:90:5, CHAIN:90:5, COOKED_PORKCHOP:90:5, CRYING_OBSIDIAN:40:2, DIAMOND:40:2, ENCHANTED_GOLDEN_APPLE:20:1, GILDED_BLACKSTONE:90:5, GOLD_BLOCK:20:1, GOLDEN_APPLE:20:1, GOLDEN_AXE:20:1, GOLDEN_HELMET:20:1, GOLDEN_CARROT:40:2, GOLD_NUGGET:90:5, GOLD_INGOT:90:5, IRON_BLOCK:20:1, IRON_INGOT:90:5, IRON_NUGGET:90:5, IRON_SWORD:20:1, MAGMA_CREAM:90:5, MUSIC_DISC_PIGSTEP:20:1, NETHERITE_UPGRADE_SMITHING_TEMPLATE:20:1, OBSIDIAN:40:2, SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE:20:1, SPECTRAL_ARROW:90:5, STRING:90:5]
    Biomes: [BASALT_DELTAS]
  Vanilla_Nether:
    LootTables:
      - BASTION_BRIDGE:
          - Weight: 100
      - BASTION_HOGLIN_STABLE:
          - Weight: 100
      - BASTION_OTHER:
          - Weight: 100
      - BASTION_TREASURE:
          - Weight: 100
      - NETHER_BRIDGE:
          - Weight: 100
    Biomes:
      - CRIMSON_FOREST
      - NETHER_WASTES
      - SOUL_SAND_VALLEY
      - WARPED_FOREST
#
# End Biomes Example:
#
  Custom_Chest4:
    Items: [DIAMOND:40:2, DRAGON_EGG:20:1, DRAGON_HEAD:20:1, ELYTRA:20:1, END_CRYSTAL:20:1, ENDER_CHEST:20:1, END_ROD:90:5, GOLD_INGOT:90:5, IRON_INGOT:90:5, MAGENTA_STAINED_GLASS:90:5, OBSIDIAN:90:5]
    Biomes: [END_BARRENS, SMALL_END_ISLANDS, THE_END]
  Vanilla_End:
    LootTables:
      - END_CITY_TREASURE:
          - Weight: 100
    Biomes:
      - END_HIGHLANDS
      - END_MIDLANDS