name: SkyGrid
version: 1.21
main: main.SkyGridPlugin
author: Go0fy_Go0ber
description: A plugin that generates a SkyGrid and more.
api-version: 1.17
commands:
  tpr:
    description: Teleport to a random location in the overworld, nether or end
    permission: sg.tpr
    usage: /tpr
  tpro:
    description: Teleport to a random location in the overworld
    permission: sg.tpr.overworld
    usage: /tpro
  tprn:
    description: Teleport to a random location in the nether
    permission: sg.tpr.nether
    usage: /tprn
  tpre:
    description: Teleport to a random location in the end
    permission: sg.tpr.end
    usage: /tpre
  fogon:
    description: Enable fog
    permission: sg.fogon
    usage: /fogon
    default: op
  fogoff:
    description: Disable fog
    permission: sg.fogoff
    usage: /fogoff
  eclogson:
    description: Enable Event Control logging
    permission: sg.eclogson
    usage: /eclogson
  eclogsoff:
    description: Disable Event Control logging
    permission: sg.eclogsoff
    usage: /eclogsoff
  pregen:
    description: Enable pre-generation with customizable parameters
    permission: sg.pregen
    usage: /pregen <ParallelTasksMultiplier> <PrintUpdateDelayin(Seconds/Minutes/Hours)> <world> <Radius(Blocks/Chunks/Regions)>
  pregenoff:
    description: Disable pre-generation
    permission: sg.pregenoff
    usage: /pregenoff
  patch:
    description: Patch files to update materials and entities to another version
    permission: sg.patch
    usage: /patch
  regen:
    description: Regenerate all loaded chunks
    permission: sg.regen
    usage: /regen
permissions:
  sg.tpr:
    description: Allows teleportation to overworld, nether and end using the /tpr command
    default: true
  sg.tpr.overworld:
    description: Grants permission to use the /tpro command for teleportation for the overworld
    default: true
  sg.tpr.nether:
    description: Grants permission to use the /tprn command for teleportation for the Nether
    default: true
  sg.tpr.end:
    description: Enables usage of the /tpre command for teleportation for the End
    default: true
  sg.tpr.*:
    description: Provides access to all teleportation commands
    default: op
    children:
      sg.tpr: true
      sg.tpr.overworld: true
      sg.tpr.nether: true
      sg.tpr.end: true
  sg.fogon:
    description: Allows enabling fog using the /fogon command
    default: op
  sg.fogoff:
    description: Allows disabling fog with the /fogoff command
    default: op
  sg.eclogson:
    description: Grants permission to enable Event Control logging using /eclogson
    default: op
  sg.eclogsoff:
    description: Grants permission to disable Event Control logging using /eclogsoff
    default: op
  sg.pregen:
    description: Grants permission to use the pre-generation command with customizable parameters
    default: op
  sg.pregenoff:
    description: Grants permission to disable pre-generation using the /pregenoff command
    default: op
  sg.patch:
    description: Allows patching files to update materials and entities to another version
    default: op
  sg.regen:
    description: Grants permission to regenerate all loaded chunks using the /regen command
    default: op
  sg.*:
    description: Provides access to all SkyGrid commands
    default: op
    children:
      sg.tpr: true
      sg.tpr.overworld: true
      sg.tpr.nether: true
      sg.tpr.end: true
      sg.fogon: true
      sg.fogoff: true
      sg.eclogson: true
      sg.eclogsoff: true
      sg.pregen: true
      sg.pregenoff: true
      sg.patch: true
      sg.regen: true